# Imports
import = ["~/.config/alacritty/dracula.toml"]

[window]
padding = { x = 5, y = 5 }
decorations = "None"
opacity = 0.85

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 16

[cursor]
style = {shape = "Beam", blinking = "On"}

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"
