# Imports
import = ["~/.config/alacritty/dracula.toml"]

[window]
padding = { x = 5, y = 5 }
decorations = "None"
opacity = 1.0
blur = false

[font]
normal = { family = "JetBrains Mono", style = "Medium" }
size = 12

[cursor]
style = {shape = "Beam", blinking = "On"}
