
[window]
padding = { x = 5, y = 5 }
decorations = "None"
opacity = 0.75

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 15

[cursor]
style = {shape = "Beam", blinking = "On"}

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[general]
# Imports
import = ["~/.config/alacritty/colors.toml"]
